### ISSUE TITLE
DOC - Viết liệu học thuật mô tả khái quát hệ thống

### ISSUE THREAD

**Issue by vietcoder1998** [vietcoder1998/he-thong-chuan-doan-xu-ly-lam-sang-va-tien-lam-sang-y-khoa#1]
## MÔ TẢ
- Lên document triển khai hệ thống chuẩn chỉnh để người dùng có thể mường tượng được hệ thống hoạt động như thế nào, cách vận hành ra sao, doanh thu chiến lược kinh doanh như thế nào
- Sát với thực tế, không được gian dối số liệu.
## TODO

- [ ] - Viết và dựng tài liệu mô tả
- [ ] - Viết và dựng base QA cho hệ thống
- [ ] - Viết và dựng Diagram cho hệ thống
